CREATE TABLE raw_311_data (
    case_enquiry_id BIGINT PRIMARY KEY,
    open_dt TIMESTAMP,
    sla_target_dt TIMESTAMP,
    closed_dt TIMESTAMP,
    on_time VARCHAR(20),
    case_status VARCHAR(20),
    closure_reason TEXT,
    case_title TEXT,
    subject VARCHAR(100),
    reason VARCHAR(100),
    type VARCHAR(100),
    queue VARCHAR(100),
    department VARCHAR(100),
    submitted_photo TEXT,
    closed_photo TEXT,
    location TEXT,
    fire_district VARCHAR(10),
    pwd_district VARCHAR(10),
    city_council_district VARCHAR(10),
    police_district VARCHAR(10),
    neighborhood VARCHAR(100),
    neighborhood_services_district VARCHAR(10),
    ward VARCHAR(20),
    precinct VARCHAR(10),
    location_street_name TEXT,
    location_zipcode VARCHAR(10),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    geom_4326 TEXT,
    source VARCHAR(100)
);
